import os
from dotenv import load_dotenv

load_dotenv()

AUTH_SERVICE_URL = os.getenv("AUTH_SERVICE_URL")
PETS_SERVICE_URL = os.getenv("PETS_SERVICE_URL")
APPOINTMENTS_SERVICE_URL = os.getenv("APPOINTMENTS_SERVICE_URL")
RECOMPENSAS_SERVICE_URL = os.getenv("RECOMPENSAS_SERVICE_URL")
SEGUIMIENTO_SERVICE_URL = os.getenv("SEGUIMIENTO_SERVICE_URL")
